require("lua.global.plugins")
require("lua.global.options")
require("lua.global.keymaps")
require("lua.global.functions")

require("lua.plugins.cmp")
require("lua.plugins.comment")
require("lua.plugins.fidget")
require("lua.plugins.gitsigns")
require("lua.plugins.harpoon")
require("lua.plugins.indent_blankline")
require("lua.plugins.lsp")
require("lua.plugins.lualine")
require("lua.plugins.neodev")
require("lua.plugins.nvimtree")
require("lua.plugins.telescope")
require("lua.plugins.treesitter")
