require("global.plugins")
require("global.options")
require("global.keymaps")
require("global.functions")
require("global.autocommands")

require("plugins.cmp")
require("plugins.colorizer")
require("plugins.surround")
require("plugins.dap-ui")
require("plugins.comment")
require("plugins.fidget")
require("plugins.gitsigns")
require("plugins.harpoon")
require("plugins.indent_blankline")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.neodev")
require("plugins.nvimtree")
require("plugins.telescope")
require("plugins.treesitter")
-- require("plugins.one-monokai")
